### PR TITLE
adds delete functionality, adds post title, fixes minor design.

### LINKED ISSUE #26: Add ingerdients and steps
-Add ingredients when clicking the add button, in a list.
-Add how to prepare steps when clicking on the add button, in a list.

### PR DESCRIPTION
**Pull request by aysam199**
-Ingredients and steps are aligned to the left now.
-Adds the delete functionality.
-Adds input field for the post title.
-Fixed a bug where when entering a lot of text the ingredients/steps stops showing, now it breaks lines and shows them well.
-Bit of design fixes.

rel #38 
rel #9
closes #26

### CODE REVIEW

File: src/pages/AddPost/components/NewPostBody/index.jsx [hunk 1]
```diff
@@ -35,11 +35,22 @@ export default function NewPostBody({
     setIngredientName(event.target.value);
   const handleIngredients = event =>
     setIngredients({ ...ingredients, [ingredientName]: ingredientQuantity });
+  const deleteIngredient = key => event => {
+    delete ingredients[key]
+    setIngredients({...ingredients});
+  }
```
Comment (okarem) [inline src/pages/AddPost/components/NewPostBody/index.jsx:42]: add the title state and setter here please

**Review by okarem — CHANGES_REQUESTED** [review]

**Review by okarem — APPROVED** [review]
